//! The All Values In Category
// value: 'all';
// value: 'css';
// value: 'js';
// value: 'react';
// value: 'node';

export const myProjects = [
  {
    id: 1,
    img: '/public/image/one.png',
    title: 'Leon - Super ',
    text: 'Fist Project',
    linkProject: 'https://ahmedesam-415.github.io/Project_One/',
    linkGitHub: 'https://github.com/AhmedEsam-415/Project_One',
    Category: 'css',
  },
  {
    id: 2,
    img: '/public/image/two.png',
    title: 'Kasper',
    text: 'Second Project',
    linkProject: 'https://ahmedesam-415.github.io/Project_Two/',
    linkGitHub: 'https://github.com/AhmedEsam-415/Project_Two',
    Category: 'css',
  },
  {
    id: 3,
    img: '/public/image/three.png',
    title: 'NovaCorner',
    text: 'Thred Project',
    linkProject: 'https://ahmedesam-415.github.io/Project_Three/',
    linkGitHub: 'https://github.com/AhmedEsam-415/Project_Three',
    Category: 'css',
  },
  {
    id: 4,
    img: '/public/image/four.png',
    title: 'Dashboard',
    text: 'Ford Project',
    linkProject: 'https://ahmedesam-415.github.io/Project_Four/',
    linkGitHub: 'https://github.com/AhmedEsam-415/Project_Four',
    Category: 'css',
  },
  {
    id: 5,
    img: '/public/image/bondi.png',
    title: 'Bondi',
    text: 'Five Project',
    linkProject: 'https://ahmedesam-415.github.io/Bootstrap/',
    linkGitHub: 'https://github.com/AhmedEsam-415/Bootstrap',
    Category: ['css', 'bootstrap'],
  },
  {
    id: 6,
    img: '',
    title: '',
    text: '',
    linkProject: '',
    linkGitHub: '',
    Category: '',
  },
  {
    id: 7,
    img: '',
    title: '',
    text: '',
    linkProject: '',
    linkGitHub: '',
    Category: '',
  },
  {
    id: 8,
    img: '',
    title: '',
    text: '',
    linkProject: '',
    linkGitHub: '',
    Category: '',
  },
  {
    id: 9,
    img: '',
    title: '',
    text: '',
    linkProject: '',
    linkGitHub: '',
    Category: '',
  },
  {
    id: 10,
    img: '',
    title: '',
    text: '',
    linkProject: '',
    linkGitHub: '',
    Category: '',
  },
  {
    id: 11,
    img: '',
    title: '',
    text: '',
    linkProject: '',
    linkGitHub: '',
    Category: '',
  },
  {
    id: 12,
    img: '',
    title: '',
    text: '',
    linkProject: '',
    linkGitHub: '',
    Category: '',
  },
];
